name: voice_voyage
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2

  firebase_core: ^3.12.0       
  firebase_auth: ^5.3.0        
  cloud_firestore: ^5.5.0   

  #azure_speech_assessment: ^0.0.7
 # azure_speech_recognition_null_safety: ^0.9.6
 # permission_handler: ^11.0.0   

#  flutter_azure_speech: ^0.0.6
  http: ^1.2.2
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^11.0.0
  flutter_sound: ^9.30.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
